// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0KIKOy228TIzYXmfmJkfXicPGJY5SuY',
    appId: '1:376454246757:web:91ecd9c41547e3eccab18c',
    messagingSenderId: '376454246757',
    projectId: 'industry-temp-monitor',
    authDomain: 'industry-temp-monitor.firebaseapp.com',
    databaseURL:
        'https://industry-temp-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'industry-temp-monitor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxphE7EdmYPRTcqxUy2k8WoBjrop5fBMw',
    appId: '1:376454246757:android:4cf293426c66f7ebcab18c',
    messagingSenderId: '376454246757',
    projectId: 'industry-temp-monitor',
    databaseURL:
        'https://industry-temp-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'industry-temp-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX5XiR8IdGrQQfQJPUBskVmfniGm7rsM8',
    appId: '1:376454246757:ios:10f5f395bce248d2cab18c',
    messagingSenderId: '376454246757',
    projectId: 'industry-temp-monitor',
    databaseURL:
        'https://industry-temp-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'industry-temp-monitor.firebasestorage.app',
    iosBundleId: 'com.example.industrialTemperatureMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX5XiR8IdGrQQfQJPUBskVmfniGm7rsM8',
    appId: '1:376454246757:ios:10f5f395bce248d2cab18c',
    messagingSenderId: '376454246757',
    projectId: 'industry-temp-monitor',
    databaseURL:
        'https://industry-temp-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'industry-temp-monitor.firebasestorage.app',
    iosBundleId: 'com.example.industrialTemperatureMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn0KIKOy228TIzYXmfmJkfXicPGJY5SuY',
    appId: '1:376454246757:web:b5fc03a7c68965eacab18c',
    messagingSenderId: '376454246757',
    projectId: 'industry-temp-monitor',
    authDomain: 'industry-temp-monitor.firebaseapp.com',
    databaseURL:
        'https://industry-temp-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'industry-temp-monitor.firebasestorage.app',
  );
}
