; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Serial Monitor configuration
monitor_speed = 115200

; Library Dependencies
;Onewire Library - Used to enable the one wire protocol on the GPIO 4
;DallasTemperature - Sits on top of the OneWire library,It translates the 64-bit addresses and pulses from the DS18B20 sensors into human readable celcius values.
;PID library - you give it current temperature and target temperature,it outputs a PWM signal 
lib_deps = 
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    br3ttb/PID
    marcoschwartz/LiquidCrystal_I2C
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32